services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3003:3000" # Puerto externo 3003, interno 3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana_dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./grafana-provisioning:/etc/grafana/provisioning

  locust:
    build:
      context: ./locust
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    logging:
      driver: none

  hst-service:
    build:
      context: ./hst
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  grafana-storage:
