{
 "title": "flask transaction",
 "description": "Flask",
 "tags": [ "flask" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Endpoint1 response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{path=\"/api/v1/endpoint1\", status='200'}[30s])\r\n/\r\nrate(flask_http_request_duration_seconds_count{path=\"/api/v1/endpoint1\", status='200'}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomaly Score",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anomaly_score", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "Endpoint2 response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{path=\"/api/v1/endpoint2\", status='200'}[30s])\r\n/\r\nrate(flask_http_request_duration_seconds_count{path=\"/api/v1/endpoint2\", status='200'}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint3 response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{path=\"/api/v1/endpoint3\", status='200'}[30s])\r\n/\r\nrate(flask_http_request_duration_seconds_count{path=\"/api/v1/endpoint3\", status='200'}[30s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}